### ISSUE TITLE
子项目的权限路由

### ISSUE THREAD

**Issue by yuguaa** [gongshun/qiankun-vue-element-admin#3]
子项目的permission文件引入,却不能正常走全局路由钩子

![permission1](https://static01.imgkr.com/temp/b4a719570d254a2d83575b1ae651d8de.png)
![permission2](https://static01.imgkr.com/temp/8072574db4a24c958405fbd96367e499.png)

**Comment by yuguaa** [comment]
https://static01.imgkr.com/temp/8072574db4a24c958405fbd96367e499.png

https://static01.imgkr.com/temp/cb870cd4b5d3483db1bd953f3bf31b5a.png

**Comment by gongshun** [comment]
因为根本没有用那个 `router` 实例，在 `mian.js` 重新 `new Router` 的，路由钩子应该写在这里，https://github.com/gongshun/qiankun-vue-element-admin/blob/07183d4783266a199692f277902989c97bbbda47/vue-admin-child/src/main.js#L44

**Comment by yuguaa** [comment]
我之前这样写会报路由实例已存在。
另外，这样的话，子项目单独跑就没了权限路由了，引入permission.js的意义就没有了

**Comment by gongshun** [comment]
> 我之前这样写会报路由实例已存在。
> 另外，这样的话，子项目单独跑就没了权限路由了，引入permission.js的意义就没有了

在 main.js 里面的 render 函数里面写路由钩子就行了，单独运行还是会执行的
